# ruff: noqa: F821
# pyright: reportUndefinedVariable=false
# `c` is a global injected by qutebrowser

c.colors.completion.fg = '#EDEDED'
c.colors.completion.odd.bg = '#1B1B1B'
c.colors.completion.even.bg = '#181818'
c.colors.completion.category.fg = '#CCD5E4'
c.colors.completion.category.bg = '#181818'
c.colors.completion.category.border.top = '#181818'
c.colors.completion.category.border.bottom = '#181818'
c.colors.completion.item.selected.fg = '#EDEDED'
c.colors.completion.item.selected.bg = '#282F38'
c.colors.completion.item.selected.border.top = '#282F38'
c.colors.completion.item.selected.border.bottom = '#282F38'
c.colors.completion.item.selected.match.fg = '#FF570D'
c.colors.completion.match.fg = '#FF570D'
c.colors.completion.scrollbar.fg = '#707B84'
c.colors.completion.scrollbar.bg = '#181818'

c.colors.contextmenu.disabled.bg = '#1B1B1B'
c.colors.contextmenu.disabled.fg = '#707B84'
c.colors.contextmenu.menu.bg = '#181818'
c.colors.contextmenu.menu.fg = '#EDEDED'
c.colors.contextmenu.selected.bg = '#282F38'
c.colors.contextmenu.selected.fg = '#EDEDED'

c.colors.downloads.bar.bg = '#181818'
c.colors.downloads.start.fg = '#EDEDED'
c.colors.downloads.start.bg = '#CCD5E4'
c.colors.downloads.stop.fg = '#EDEDED'
c.colors.downloads.stop.bg = '#97B5A6'
c.colors.downloads.error.fg = '#FF7B72'

c.colors.hints.fg = '#181818'
c.colors.hints.bg = '#ff8a31'
c.colors.hints.match.fg = '#707B84'

c.colors.keyhint.fg = '#EDEDED'
c.colors.keyhint.suffix.fg = '#ff8a31'
c.colors.keyhint.bg = '#181818'

c.colors.messages.error.fg = '#EDEDED'
c.colors.messages.error.bg = '#FF7B72'
c.colors.messages.error.border = '#FF7B72'
c.colors.messages.warning.fg = '#EDEDED'
c.colors.messages.warning.bg = '#FF570D'
c.colors.messages.warning.border = '#FF570D'
c.colors.messages.info.fg = '#EDEDED'
c.colors.messages.info.bg = '#181818'
c.colors.messages.info.border = '#181818'

c.colors.prompts.fg = '#EDEDED'
c.colors.prompts.border = '#292826'
c.colors.prompts.bg = '#1B1B1B'
c.colors.prompts.selected.fg = '#EDEDED'
c.colors.prompts.selected.bg = '#282F38'

c.colors.statusbar.normal.fg = '#EDEDED'
c.colors.statusbar.normal.bg = '#181818'
c.colors.statusbar.insert.fg = '#181818'
c.colors.statusbar.insert.bg = '#97B5A6'
c.colors.statusbar.passthrough.fg = '#181818'
c.colors.statusbar.passthrough.bg = '#CCD5E4'
c.colors.statusbar.private.fg = '#EDEDED'
c.colors.statusbar.private.bg = '#1B1B1B'
c.colors.statusbar.command.fg = '#EDEDED'
c.colors.statusbar.command.bg = '#181818'
c.colors.statusbar.command.private.fg = '#EDEDED'
c.colors.statusbar.command.private.bg = '#181818'
c.colors.statusbar.caret.fg = '#181818'
c.colors.statusbar.caret.bg = '#8A92A7'
c.colors.statusbar.caret.selection.fg = '#181818'
c.colors.statusbar.caret.selection.bg = '#8A92A7'
c.colors.statusbar.progress.bg = '#CCD5E4'
c.colors.statusbar.url.fg = '#EDEDED'
c.colors.statusbar.url.error.fg = '#FF7B72'
c.colors.statusbar.url.hover.fg = '#8A9AA6'
c.colors.statusbar.url.success.http.fg = '#707B84'
c.colors.statusbar.url.success.https.fg = '#97B5A6'
c.colors.statusbar.url.warn.fg = '#FF570D'

c.colors.tabs.bar.bg = '#181818'
c.colors.tabs.indicator.start = '#CCD5E4'
c.colors.tabs.indicator.stop = '#97B5A6'
c.colors.tabs.indicator.error = '#FF7B72'
c.colors.tabs.odd.fg = '#C3C8C6'
c.colors.tabs.odd.bg = '#181818'
c.colors.tabs.even.fg = '#C3C8C6'
c.colors.tabs.even.bg = '#181818'
c.colors.tabs.pinned.odd.fg = '#EDEDED'
c.colors.tabs.pinned.odd.bg = '#181818'
c.colors.tabs.pinned.even.fg = '#EDEDED'
c.colors.tabs.pinned.even.bg = '#181818'
c.colors.tabs.pinned.selected.odd.fg = '#EDEDED'
c.colors.tabs.pinned.selected.odd.bg = '#292826'
c.colors.tabs.pinned.selected.even.fg = '#EDEDED'
c.colors.tabs.pinned.selected.even.bg = '#292826'
c.colors.tabs.selected.odd.fg = '#EDEDED'
c.colors.tabs.selected.odd.bg = '#292826'
c.colors.tabs.selected.even.fg = '#EDEDED'
c.colors.tabs.selected.even.bg = '#292826'

c.colors.webpage.bg = '#181818'
